apiVersion: virtualenvironment.proxmoxbpg.m.crossplane.io/v1alpha1
kind: EnvironmentCertificate
metadata:
  annotations:
    meta.upbound.io/example-id: virtualenvironment/v1alpha1/environmentcertificate
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    certificate: ${tls_self_signed_cert.proxmox_virtual_environment_certificate.cert_pem}
    nodeName: first-node
    privateKeySecretRef:
      key: attribute.private_key_pem
      name: example-private-key
