apiVersion: virtualenvironmentaptrepository.proxmoxbpg.m.crossplane.io/v1alpha1
kind: EnvironmentAptRepository
metadata:
  annotations:
    meta.upbound.io/example-id: virtualenvironmentaptrepository/v1alpha1/environmentaptrepository
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    enabled: true
    filePath: /etc/apt/sources.list
    index: 0
    node: pve
