apiVersion: virtualenvironmenthagroup.proxmoxbpg.m.crossplane.io/v1alpha1
kind: EnvironmentHagroup
metadata:
  annotations:
    meta.upbound.io/example-id: virtualenvironmenthagroup/v1alpha1/environmenthagroup
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    comment: This is a comment.
    group: example
    noFailback: false
    nodes:
      node1: null
      node2: 2
      node3: 1
    restricted: true
