apiVersion: virtualenvironmentnetworklinuxbridge.proxmoxbpg.m.crossplane.io/v1alpha1
kind: EnvironmentNetworkLinuxBridge
metadata:
  annotations:
    meta.upbound.io/example-id: virtualenvironmentnetworklinuxbridge/v1alpha1/environmentnetworklinuxbridge
  labels:
    testing.upbound.io/example-name: vmbr99
  name: vmbr99
  namespace: crossplane-system
spec:
  forProvider:
    address: 99.99.99.99/16
    comment: vmbr99 comment
    name: vmbr99
    nodeName: pve
    ports:
    - ens18.99

---

apiVersion: virtualenvironmentnetworklinuxvlan.proxmoxbpg.m.crossplane.io/v1alpha1
kind: EnvironmentNetworkLinuxVlan
metadata:
  annotations:
    meta.upbound.io/example-id: virtualenvironmentnetworklinuxbridge/v1alpha1/environmentnetworklinuxbridge
  labels:
    testing.upbound.io/example-name: vlan99
  name: vlan99
  namespace: crossplane-system
spec:
  forProvider:
    name: ens18.99
    nodeName: pve
