apiVersion: virtualenvironmentacmednsplugin.proxmoxbpg.m.crossplane.io/v1alpha1
kind: EnvironmentAcmeDNSPlugin
metadata:
  annotations:
    meta.upbound.io/example-id: virtualenvironmentacmednsplugin/v1alpha1/environmentacmednsplugin
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    api: aws
    data:
      AWS_ACCESS_KEY_ID: EXAMPLE
      AWS_SECRET_ACCESS_KEY: EXAMPLE
    plugin: test
